### ISSUE TITLE
Error when running `pulp test` after updating all required dependencies

### ISSUE THREAD

**Issue by ulyssesp** [paf31/purescript-thermite#60]
Running `pulp test` after running `bower update` and `npm install` produces this error. It also happens in a project using purescript-thermite. purescript-react runs as expected.

```
c:\Users\Ulysses\Development\purescript-thermite\output\React.DOM\index.js:21
            return createElement(tag)(React_DOM_Props.unsafeFromPropsArray(props));
                   ^

TypeError: createElement is not a function
    at c:\Users\Ulysses\Development\purescript-thermite\output\React.DOM\index.js:21:20
    at Object.<anonymous> (c:\Users\Ulysses\Development\purescript-thermite\output\React.DOM\index.js:26:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\Ulysses\Development\purescript-thermite\output\Thermite\index.js:22:17)
    at Module._compile (module.js:398:26)
* ERROR: Subcommand terminated with exit code 1
```

**Comment by paf31** [comment]
Use `pulp test -r cat > html/index.js` if you want to run the test project.
